### ISSUE TITLE
can not flash shex firmware ... 

### ISSUE THREAD

**Issue by PG3rd** [mame82/munifying#5]
I had successfully flashed the firmware 1 year ago, but this time it didn't work. I have installed libusb and compiled munifying successfully, the usb receiver is cu0008, everything looks right, but it still reports errors, can you please tell me what the following possible problems are?
Thank you very much!

ubuntu 22.04 LTS 

sudo ./munifying flash -f 1.shex
Trying to flash hex file '1.shex'
Parsing firmware hex file '1.shex'
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/mame82/munifying/unifying.ParseFirmwareHex({0x7ffece2a5862, 0x6})
	/home/pg3rd/GOPATH/src/munifying-master/unifying/firmware_parser.go:387 +0x68a
github.com/mame82/munifying/cmd.FlashFirmwareFromHexFile({0x7ffece2a5862?, 0xc0000a8008?}, {0x0, 0x0})
	/home/pg3rd/GOPATH/src/munifying-master/cmd/flash.go:35 +0x45
github.com/mame82/munifying/cmd.glob..func3(0x745fe0?, {0x5e810c?, 0x2?, 0x2?})
	/home/pg3rd/GOPATH/src/munifying-master/cmd/flash.go:166 +0x438
github.com/spf13/cobra.(*Command).execute(0x745fe0, {0xc0000b40a0, 0x2, 0x2})
	/home/pg3rd/GOPATH/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x7469e0)
	/home/pg3rd/GOPATH/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2ef
github.com/spf13/cobra.(*Command).Execute(...)
	/home/pg3rd/GOPATH/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/mame82/munifying/cmd.Execute()
	/home/pg3rd/GOPATH/src/munifying-master/cmd/root.go:44 +0x25
main.main()
	/home/pg3rd/GOPATH/src/munifying-master/main.go:26 +0x17

**Comment by PG3rd** [comment]
Solved, it was my mistake, I was using the wrong shex firmware ...... Thanks again!
